# Generated by Django 5.1 on 2025-02-13 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=40)),
                ('color', models.CharField(default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField()),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=1)),
                ('horas', models.CharField(max_length=20)),
                ('dias', models.CharField(max_length=100)),
                ('cupo', models.IntegerField()),
                ('calificacion', models.FloatField(default=0.0)),
                ('salon', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-calificacion'],
            },
        ),
        migrations.CreateModel(
            name='GruposAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupos', models.ManyToManyField(to='horarios.grupo')),
            ],
            options={
                'verbose_name': 'GruposDeAlumno',
                'verbose_name_plural': 'GruposDeAlumnos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horarios.color')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['clave'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.materia'),
        ),
        migrations.CreateModel(
            name='MateriasAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('materias', models.ManyToManyField(to='horarios.materia')),
            ],
            options={
                'verbose_name': 'MateriasAlumno',
                'verbose_name_plural': 'MateriasDeAlumnos',
            },
        ),
    ]
